name: Buildroot Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # Mantenemos esto para que no se quede esperando
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential cpio file python3 rsync unzip wget qemu-system-x86 valgrind netcat-openbsd

      - name: Build and Test
        run: |
          # Aquí el script de la tarea 5 ejecutará todo automáticamente
          ./full-test.sh