name: Buildroot Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive' # Esto descarga buildroot sin necesidad de SSH

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential cpio file python3 rsync unzip wget

      - name: Build
        run: |
          ./build.sh # O los comandos que uses para compilar